--CREATING A VIEW TO GET THE DETAILS OF ALL SCREENS AND CORRESPONDING MOVIES 
CREATE VIEW SCREEN_MOVIE AS
SELECT SCREEN_NAME,MOVIE_NAME
FROM
    SCREENS INNER JOIN MOVIES USING(MOVIE_ID);
    
--Getting the data of view
SELECT * FROM SCREEN_MOVIE;

--CREATING A VIEW TO GET THE DATA OF USERS
CREATE VIEW USER_VIEW AS
SELECT 
    USER_NAME,USER_PHONE_NUMBER,USER_CURRENT_CITY
FROM
    USERS;
   
 
    
--UPDATING THE UNDERLYING USER TABLE VIA USER_VIEW 
UPDATE 
    USER_VIEW
SET
    USER_NAME='Sathish'
WHERE
    USER_PHONE_NUMBER=6302232473;
    
    
--REMOVING A ROW IN UNDERLYING USER TABLE VIA USER_VIEW
DELETE FROM
    USER_VIEW
WHERE
    USER_NAME='Priya';
    
--INSERTING A NEW ROW INTO UNDERLYING USER TABLE VIA USER_VIEW
INSERT INTO
    USER_VIEW
VALUES('Shoban',9658945785,1);

--CREATING A NEW "VIEW" TO GET ALL THE USERS OF CITY "VIZAG"
CREATE OR REPLACE VIEW VIZAG_USERS AS
SELECT
    USER_NAME,USER_PHONE_NUMBER,USER_CURRENT_CITY
FROM
    USERS
WHERE
    USER_CURRENT_CITY=4 WITH CHECK OPTION;
    
--RESULT OF THIS QUERY WILL BE AN ERROR SINCE WE USED "WITH CHECK OPTION" IN VIEW
INSERT INTO VIZAG_USERS
VALUES('HITESH',9866575895,3);--Raises an error

    