CREATE TABLE CITIES
    (city_id INT GENERATED BY DEFAULT AS IDENTITY,
    city_name VARCHAR2(20) NOT NULL ,
    PRIMARY KEY(city_id));

CREATE TABLE MOVIES
        (movie_id INT GENERATED BY DEFAULT AS IDENTITY,
        movie_name VARCHAR2(50) NOT NULL,
        movie_description VARCHAR(100) ,
        movie_runtime_in_minutes INT ,
        movie_director VARCHAR(30) NOT NULL,
        PRIMARY KEY(movie_id));

CREATE TABLE CITY_MOVIE
        (city_id INT,
        movie_id INT,
         CONSTRAINT city_movie_city_constraint
        FOREIGN KEY(city_id) REFERENCES CITIES(city_id),
        CONSTRAINT city_movie_movie_constraint
        FOREIGN  KEY(movie_id) REFERENCES MOVIES(movie_id),
        PRIMARY KEY(city_id,movie_id));

CREATE TABLE USERS
        (user_id INT GENERATED BY DEFAULT AS IDENTITY,
        user_name VARCHAR2(50) NOT NULL,
        user_phone_number INT NOT NULL,
        user_email VARCHAR2(40),
        user_current_city INT,
        CONSTRAINT users_city_constraint
        FOREIGN KEY(user_current_city) REFERENCES CITIES(city_id),
        PRIMARY KEY(user_id));


CREATE TABLE SCREENS
    (screen_id INT GENERATED BY DEFAULT AS IDENTITY,
    screen_name VARCHAR2(50) NOT NULL,
    screen_address VARCHAR2(70) NOT NULL,
    movie_id INT,
    city_id INT,
    PRIMARY KEY(screen_id),
    CONSTRAINT screens_city_id 
    FOREIGN KEY(city_id) REFERENCES CITIES(city_id),
    CONSTRAINT screens_movie_id
    FOREIGN KEY(movie_id) REFERENCES MOVIES(movie_id));
    
CREATE TABLE user_screen
    (user_id INT,
    screen_id INT,
    PRIMARY KEY(user_id,screen_id),
    CONSTRAINT user_screen_user_id
    FOREIGN KEY(user_id) REFERENCES USERS(user_id),
    CONSTRAINT user_screen_screen_Id
    FOREIGN KEY(screen_id) REFERENCES SCREENS(screen_id));








